print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print("¨¨¨¨¨¨¨Curso de Estética SENAI¨¨¨¨¨¨¨¨¨¨")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
nome = input("Digite o nome do Paciente: ")
print("")
peso = float(input("Digite seu peso: "))
print("")
altura = float(input("Digite sua altura: "))
imc = float(peso / altura**2)
print("")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print("¨¨¨¨¨¨¨¨¨¨¨Ficha Técnica¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print("Nome do Paciente: ",nome)
print("Altura: ",altura)
print("Peso: ",peso)
print(f"Seu IMC: {imc:.2f}")
if (imc) > 30: print("Olá ",nome, "Você esta na categoria de OBESIDADE!")
if (imc) >= 20: print("Olá ",nome, "Você esta na categoria de PESO NORMAL!")
else : ("Olá ", nome, "Você esta na Categoria de SOBRE PESO")