print("      @                     ^")
print("      *                   +  +")
print("     ***                +      +")
print("    *****             +          +")
print("   *******          +   SENAI-SP   +")
print("  *********          --------------")
print(" ***********         |            |")
print("     |||             |            |")
print("     |||             |            |")
print("                     --------------")
print(" FELIZ NATAL      ")
